apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-results
spec:
  tasks:
  - name: generate
    taskSpec:
      results:
      - name: url
      steps:
      - name: generate
        image: registry.access.redhat.com/ubi8/ubi-minimal
        script: |
          echo "https://artifacts.mycompany.com/mypipelinerun/210908-111711/" > $(results.url.path)
          echo "Done"
  - name: test-suite-1
    runAfter:
    - generate
    taskSpec:
      steps:
      - name: test
        image: registry.access.redhat.com/ubi8/ubi-minimal
        script: |
          echo "Done"
  - name: test-suite-2
    runAfter:
    - generate
    taskSpec:
      steps:
      - name: test
        image: registry.access.redhat.com/ubi8/ubi-minimal
        script: |
          echo "Done"
  finally:
  - name: cleanup
    taskSpec:
      steps:
      - name: cleanup
        image: registry.access.redhat.com/ubi8/ubi-minimal
        script: |
          echo "Done"
  results:
  - name: artifacts-url
    value: $(tasks.generate.results.url) 
